### ISSUE TITLE
Constantly have to re-enter keychain password

### ISSUE THREAD

**Issue by jkugler** [99designs/aws-vault#211]
OS: OS X 10.12.6
Using iTerm2

I use `aws-vault exec <profile> -- comand goes here` extensively.  However, I have to enter the keychain password (sometimes twice), although I press "Always allow" every time I enter the password, and on every command I run.

Is there a way to be able to enter the keychain password only once every "configurable amount of time"?

**Comment by FernandoMiguel** [comment]
After -- press enter 
Then you are in a subshell that will last about an hour if no mfa 
You can change the ttl up to eight hours.

**Comment by lox** [comment]
We fixed some issues related to this recently. We'll get out a new release shortly.

**Comment by lox** [comment]
Try https://github.com/99designs/aws-vault/releases/tag/v4.2.0 @jkugler (thanks for the quick response @mtibben)

**Comment by jkugler** [comment]
Thank you. I'll try to give it a try tomorrow. I install it via brew, so will have to fiddle some to clear out that version and install it manually.

**Comment by lox** [comment]
We'll land it in brew next!

**Comment by endzyme** [comment]
This is still happening quite often - I get the "Allow Always" dialog for about 75% of my aws-vault exec commands.

**Comment by seanscottking** [comment]
I'm still seeing this problem as well. OSX 11 El Capitan (yes I know I need to upgrade). Installed 4.2.0 via brew.

```
$ brew cask info aws-vault
aws-vault: 4.2.0
https://github.com/99designs/aws-vault
/usr/local/Caskroom/aws-vault/4.2.0 (9.5MB)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/aws-vault.rb
==> Name
aws-vault
==> Artifacts
aws-vault-darwin-amd64 -> aws-vault (Binary)
```
